# theme = "rose_pine_moon"
theme = "everforest_dark"

[editor]
scrolloff=8
mouse = false
line-number="relative"
true-color = true
rulers = [120]
# bufferline = "always"
idle-timeout = 50
end-of-line-diagnostics = "warning"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = true

[keys.insert]
"C-s" = ["normal_mode", ":w"]

[keys.normal]
"C-j" = ["goto_next_paragraph"]
"C-k" = ["goto_prev_paragraph"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]
"G" = "goto_file_end"
"X" = "extend_line_above"
"esc" = ["collapse_selection", "keep_primary_selection"]
"C-backspace" = ":w"
"`" = "goto_word"
"L" = "goto_line_end"
"H" = "goto_first_nonwhitespace"
# a = ["append_mode", "collapse_selection"]


[keys.normal.space]
"space" = "goto_last_accessed_file"
"H" = ":toggle lsp.display-inlay-hints"

[keys.select]
"C-j" = ["goto_next_paragraph"]
"C-k" = ["goto_prev_paragraph"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
